<?php
include __DIR__ . '/../Model.php';
include __DIR__ . '/../../NPAllFunc.php';
include __DIR__ . '/../../InvoiceModelInterface.php';


class ValidateInvoice extends Model implements InvoiceModelInterface
{
    private const NUMBER = 'number';
    private const NUMBER_Z = 'number_z';
    public $data = [];

    public function __construct(...$params)
    {
        parent::__construct();
        $this->parseParams($params);
    }

    private function parseParams(array $params)
    {
        foreach($params as $value){
            foreach ($value as $k=>$val){
                $this->data[$k] = iconv('utf-8','windows-1251',$val);
            }
        }

        $this->getInvoice();
    }

    public function getInvoice()
    {
        if($this->data[self::NUMBER_Z]){
              $this->data[self::NUMBER_Z . '_value'] = Model::getDataNumber($this);

        }
        $this->creator();
    }

    private function creator()
    {
        $id_user = (int)$this->data[self::NUMBER_Z . '_value']['PROPERTIES']['CREATOR']['VALUE'];
           $users = CUser::GetList($by="id", $order="asc",
            ['ID' => $id_user],
            ['FIELDS' => ['ID', 'EMAIL', 'PERSONAL_PHONE']]
            );
            $user = $users->Fetch();
            $this->data['user'] = $user;
            return $this;
    }


}

// {"mess":{"data":[{"number_z":"\u0424\u041b-06836"}]}}

/*
 *
 * {
  "data": {
    "number_z": "ФЛ-06840",
    "number_z_value": [
      {
        "ID": "66466437",
        "~ID": "66466437",
        "NAME": "ФЛ-06840",
        "~NAME": "ФЛ-06840",
        "ACTIVE": "Y",
        "~ACTIVE": "Y",
        "IBLOCK_ELEMENT_ID": "66466437",
        "~IBLOCK_ELEMENT_ID": "66466437",
        "PROPERTY_944": "4926",
        "~PROPERTY_944": "4926",
        "PROPERTY_945": "Михайлова Елена",
        "~PROPERTY_945": "Михайлова Елена",
        "PROPERTY_946": "+79035792315",
        "~PROPERTY_946": "+79035792315",
        "PROPERTY_947": "8054",
        "~PROPERTY_947": "8054",
        "PROPERTY_948": "Нижняя Красносельская, д. 40/12 стр.11",
        "~PROPERTY_948": "Нижняя Красносельская, д. 40/12 стр.11",
        "PROPERTY_949": "Секретарь",
        "~PROPERTY_949": "Секретарь",
        "PROPERTY_950": "4852403333",
        "~PROPERTY_950": "4852403333",
        "PROPERTY_951": "9435",
        "~PROPERTY_951": "9435",
        "PROPERTY_952": "ул. Республиканская, д.3, стр.2, корп.7А",
        "~PROPERTY_952": "ул. Республиканская, д.3, стр.2, корп.7А",
        "PROPERTY_953": "29.04.2021",
        "~PROPERTY_953": "29.04.2021",
        "PROPERTY_955": "",
        "~PROPERTY_955": "",
        "PROPERTY_956": "411",
        "~PROPERTY_956": "411",
        "PROPERTY_957": "A-06840",
        "~PROPERTY_957": "A-06840",
        "PROPERTY_958": "КАССОВЫЙ ЧЕК ОБЯЗАТЕЛЬНО!!! Дата и время забора - 29.04.2021 Время -",
        "~PROPERTY_958": "КАССОВЫЙ ЧЕК ОБЯЗАТЕЛЬНО!!! Дата и время забора - 29.04.2021 Время -",
        "PROPERTY_959": "465.0000",
        "~PROPERTY_959": "465.0000",
        "PROPERTY_960": "",
        "~PROPERTY_960": "",
        "PROPERTY_962": "409",
        "~PROPERTY_962": "409",
        "PROPERTY_963": "Заявка принята",
        "~PROPERTY_963": "Заявка принята",
        "PROPERTY_964": "",
        "~PROPERTY_964": "",
        "PROPERTY_965": "",
        "~PROPERTY_965": "",
        "PROPERTY_975": "",
        "~PROPERTY_975": "",
        "PROPERTY_1097": "",
        "~PROPERTY_1097": "",
        "PROPERTY_1098": "",
        "~PROPERTY_1098": "",
        "PROPERTIES": {
          "EMAIL_PAYER": {
            "ID": "1097",
            "TIMESTAMP_X": "2021-04-28 12:51:21",
            "IBLOCK_ID": "113",
            "NAME": "Почта плательщика",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "EMAIL_PAYER",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "",
            "DESCRIPTION": "",
            "~VALUE": "",
            "~DESCRIPTION": ""
          },
          "PHONE_PAYER": {
            "ID": "1098",
            "TIMESTAMP_X": "2021-04-28 12:55:25",
            "IBLOCK_ID": "113",
            "NAME": "Телефон плательщика",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "PHONE_PAYER",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "",
            "DESCRIPTION": "",
            "~VALUE": "",
            "~DESCRIPTION": ""
          },
          "CREATOR": {
            "ID": "944",
            "TIMESTAMP_X": "2020-05-26 11:02:03",
            "IBLOCK_ID": "113",
            "NAME": "Создатель",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "CREATOR",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "UserID",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "4926",
            "DESCRIPTION": "",
            "~VALUE": "4926",
            "~DESCRIPTION": ""
          },
          "NAME_SENDER": {
            "ID": "945",
            "TIMESTAMP_X": "2020-05-26 11:02:03",
            "IBLOCK_ID": "113",
            "NAME": "ФИО отправителя",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "NAME_SENDER",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "Михайлова Елена",
            "DESCRIPTION": "",
            "~VALUE": "Михайлова Елена",
            "~DESCRIPTION": ""
          },
          "PHONE_SENDER": {
            "ID": "946",
            "TIMESTAMP_X": "2020-05-26 11:02:03",
            "IBLOCK_ID": "113",
            "NAME": "Телефон отправителя",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "PHONE_SENDER",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "+79035792315",
            "DESCRIPTION": "",
            "~VALUE": "+79035792315",
            "~DESCRIPTION": ""
          },
          "CITY_SENDER": {
            "ID": "947",
            "TIMESTAMP_X": "2020-05-26 11:02:03",
            "IBLOCK_ID": "113",
            "NAME": "Город отправителя",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "CITY_SENDER",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "E",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "6",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "8054",
            "DESCRIPTION": "",
            "~VALUE": "8054",
            "~DESCRIPTION": ""
          },
          "ADRESS_SENDER": {
            "ID": "948",
            "TIMESTAMP_X": "2020-05-26 11:02:03",
            "IBLOCK_ID": "113",
            "NAME": "Адрес отправителя",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "ADRESS_SENDER",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "Нижняя Красносельская, д. 40/12 стр.11",
            "DESCRIPTION": "",
            "~VALUE": "Нижняя Красносельская, д. 40/12 стр.11",
            "~DESCRIPTION": ""
          },
          "NAME_RECIPIENT": {
            "ID": "949",
            "TIMESTAMP_X": "2020-05-26 11:02:03",
            "IBLOCK_ID": "113",
            "NAME": "ФИО получателя",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "NAME_RECIPIENT",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "Секретарь",
            "DESCRIPTION": "",
            "~VALUE": "Секретарь",
            "~DESCRIPTION": ""
          },
          "PHONE_RECIPIENT": {
            "ID": "950",
            "TIMESTAMP_X": "2020-05-26 11:02:03",
            "IBLOCK_ID": "113",
            "NAME": "Телефон получателя",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "PHONE_RECIPIENT",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "4852403333",
            "DESCRIPTION": "",
            "~VALUE": "4852403333",
            "~DESCRIPTION": ""
          },
          "CITY_RECIPIENT": {
            "ID": "951",
            "TIMESTAMP_X": "2020-05-26 11:02:03",
            "IBLOCK_ID": "113",
            "NAME": "Город получателя",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "CITY_RECIPIENT",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "E",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "6",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "9435",
            "DESCRIPTION": "",
            "~VALUE": "9435",
            "~DESCRIPTION": ""
          },
          "ADRESS_RECIPIENT": {
            "ID": "952",
            "TIMESTAMP_X": "2020-05-26 11:02:03",
            "IBLOCK_ID": "113",
            "NAME": "Адрес получателя",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "ADRESS_RECIPIENT",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "ул. Республиканская, д.3, стр.2, корп.7А",
            "DESCRIPTION": "",
            "~VALUE": "ул. Республиканская, д.3, стр.2, корп.7А",
            "~DESCRIPTION": ""
          },
          "DATE_TAKE": {
            "ID": "953",
            "TIMESTAMP_X": "2020-06-01 21:32:26",
            "IBLOCK_ID": "113",
            "NAME": "Дата забора/передачи",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "DATE_TAKE",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "Date",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "29.04.2021",
            "DESCRIPTION": "",
            "~VALUE": "29.04.2021",
            "~DESCRIPTION": ""
          },
          "WEIGHT": {
            "ID": "955",
            "TIMESTAMP_X": "2020-05-26 11:02:03",
            "IBLOCK_ID": "113",
            "NAME": "Вес",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "WEIGHT",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "N",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "",
            "DESCRIPTION": "",
            "~VALUE": "",
            "~DESCRIPTION": ""
          },
          "STATE": {
            "ID": "956",
            "TIMESTAMP_X": "2020-06-04 23:59:52",
            "IBLOCK_ID": "113",
            "NAME": "Статус клиента",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "STATE",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "L",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "Отправитель",
            "DESCRIPTION": "",
            "VALUE_ENUM_ID": "411",
            "~VALUE": "Отправитель",
            "VALUE_ENUM": "Отправитель",
            "VALUE_XML_ID": "f6ce63cc55e28264dc0d16d279fba558",
            "VALUE_SORT": "500"
          },
          "ID_1C": {
            "ID": "957",
            "TIMESTAMP_X": "2020-05-26 12:45:53",
            "IBLOCK_ID": "113",
            "NAME": "ID 1с",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "ID_1C",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "A-06840",
            "DESCRIPTION": "",
            "~VALUE": "A-06840",
            "~DESCRIPTION": ""
          },
          "INSTRUCTIONS": {
            "ID": "958",
            "TIMESTAMP_X": "2020-05-26 12:51:53",
            "IBLOCK_ID": "113",
            "NAME": "Примечание (инструкции)",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "INSTRUCTIONS",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "КАССОВЫЙ ЧЕК ОБЯЗАТЕЛЬНО!!! Дата и время забора - 29.04.2021 Время -",
            "DESCRIPTION": "",
            "~VALUE": "КАССОВЫЙ ЧЕК ОБЯЗАТЕЛЬНО!!! Дата и время забора - 29.04.2021 Время -",
            "~DESCRIPTION": ""
          },
          "SUMM": {
            "ID": "959",
            "TIMESTAMP_X": "2020-05-26 16:32:27",
            "IBLOCK_ID": "113",
            "NAME": "Сумма оплаты",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "SUMM",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "N",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "465",
            "DESCRIPTION": "",
            "~VALUE": "465.0000",
            "~DESCRIPTION": ""
          },
          "CHECK": {
            "ID": "960",
            "TIMESTAMP_X": "2020-05-26 15:05:11",
            "IBLOCK_ID": "113",
            "NAME": "Кассовый чек",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "CHECK",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "",
            "DESCRIPTION": "",
            "~VALUE": "",
            "~DESCRIPTION": ""
          },
          "TYPE_PAYMENT": {
            "ID": "962",
            "TIMESTAMP_X": "2020-06-01 23:04:54",
            "IBLOCK_ID": "113",
            "NAME": "Тип оплаты",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "TYPE_PAYMENT",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "L",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "Y",
            "FILTRABLE": "Y",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "безналичный расчет",
            "DESCRIPTION": "",
            "VALUE_ENUM_ID": "409",
            "~VALUE": "безналичный расчет",
            "VALUE_ENUM": "безналичный расчет",
            "VALUE_XML_ID": "aea49ca0688848f11e996eb4a243f386",
            "VALUE_SORT": "500"
          },
          "STATE_DEV": {
            "ID": "963",
            "TIMESTAMP_X": "2020-06-22 16:30:56",
            "IBLOCK_ID": "113",
            "NAME": "Текущий статус отправления",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "STATE_DEV",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "Заявка принята",
            "DESCRIPTION": "",
            "~VALUE": "Заявка принята",
            "~DESCRIPTION": ""
          },
          "INVOICE_NUMBER": {
            "ID": "964",
            "TIMESTAMP_X": "2020-06-22 12:45:36",
            "IBLOCK_ID": "113",
            "NAME": "Номер трека",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "INVOICE_NUMBER",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "",
            "DESCRIPTION": "",
            "~VALUE": "",
            "~DESCRIPTION": ""
          },
          "DELIVERED": {
            "ID": "965",
            "TIMESTAMP_X": "2020-06-22 16:30:28",
            "IBLOCK_ID": "113",
            "NAME": "Отметка Доставлено",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "DELIVERED",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "S",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "",
            "DESCRIPTION": "",
            "~VALUE": "",
            "~DESCRIPTION": ""
          },
          "PAYER": {
            "ID": "975",
            "TIMESTAMP_X": "2020-07-17 13:26:03",
            "IBLOCK_ID": "113",
            "NAME": "Плательщик",
            "ACTIVE": "Y",
            "SORT": "500",
            "CODE": "PAYER",
            "DEFAULT_VALUE": "",
            "PROPERTY_TYPE": "L",
            "ROW_COUNT": "1",
            "COL_COUNT": "30",
            "LIST_TYPE": "L",
            "MULTIPLE": "N",
            "XML_ID": "",
            "FILE_TYPE": "",
            "MULTIPLE_CNT": "5",
            "TMP_ID": "",
            "LINK_IBLOCK_ID": "0",
            "WITH_DESCRIPTION": "N",
            "SEARCHABLE": "N",
            "FILTRABLE": "N",
            "IS_REQUIRED": "N",
            "VERSION": "2",
            "USER_TYPE": "",
            "USER_TYPE_SETTINGS": "",
            "HINT": "",
            "VALUE": "",
            "DESCRIPTION": "",
            "VALUE_ENUM_ID": "",
            "~VALUE": "",
            "VALUE_ENUM": "",
            "VALUE_XML_ID": "",
            "VALUE_SORT": ""
          }
        }
      }
    ]
  }
}
 *
 * */